---
Name: partialformroutes
After:
  - '#rootroutes'
---
SilverStripe\Control\Director:
  rules:
    'partialuserform//$Action/$ID/$OtherID': Firesphere\PartialUserForms\Controllers\PartialSubmissionController
    'partial': Firesphere\PartialUserForms\Controllers\PartialUserFormController
