---
Name: partialformroutes
After:
  - '#rootroutes'
---
SilverStripe\Control\Director:
  rules:
    'partialuserform//$Action/$ID/$OtherID': Firesphere\PartialUserForms\Controllers\PartialSubmissionController
    'partial/$Key/$Token': Firesphere\PartialUserForms\Controllers\PartialUserFormController
    'verify': Firesphere\PartialUserForms\Controllers\PartialUserFormVerifyController
